"""Evidence engine.

Fix recommendations are not generated by the language model. They are computed
from outcomes in a reference class of comparable incidents and ranked by the
lower bound of a Wilson score interval on full recovery, so a fix that worked
9 times out of 10 is not ranked above one that worked 160 times out of 200.

The reference class starts from every incident of the diagnosed type and is
narrowed by vertical, platform and business model only while it stays large
enough to support statistics.
"""

from dataclasses import dataclass

import numpy as np

from .utils import safe_float, sub, wilson_lower
from .vocab import FIX_BY_NAME, INCIDENTS


@dataclass
class ReferenceClass:
    rows: np.ndarray
    description: str
    narrowed_by: list


def reference_class(index, incident_key, analysis, filters=None, min_cases=200):
    code = index.code_of("incident_type", INCIDENTS[incident_key]["name"])
    current = index.codes["incident_type"] == code
    for column, wanted in (filters or {}).items():
        if column in index.codes and wanted not in (None, "", []):
            values = wanted if isinstance(wanted, (list, tuple, set)) else [wanted]
            codes = [c for c in (index.code_of(column, v) for v in values) if c is not None]
            current &= np.isin(index.codes[column], codes)
    narrowed = []
    for column, value in (("vertical", analysis.vertical), ("platform", analysis.platform),
                          ("business_model", analysis.business_model)):
        if not value:
            continue
        trial = current & (index.codes[column] == index.code_of(column, value))
        if int(trial.sum()) >= min_cases:
            current = trial
            narrowed.append(value)
    rows = np.flatnonzero(current)
    desc = "{} incidents of {}".format(len(rows), INCIDENTS[incident_key]["name"].lower())
    if narrowed:
        desc += " in " + ", ".join(narrowed)
    return ReferenceClass(rows=rows, description=desc, narrowed_by=narrowed)


def fix_stats(index, rows, min_n=8):
    """Outcome statistics for every fix used in the reference class."""
    if len(rows) == 0:
        return [], 0.0
    fix_codes = index.codes["fix_strategy"][rows].astype(int)
    rec_labels = index.labels["recovery_status"]
    rec = index.codes["recovery_status"][rows]
    full = (rec == rec_labels.index("Full Recovery")).astype(float)
    anyrec = (rec != rec_labels.index("Not Recovered")).astype(float)
    repeat = (index.codes["repeat_incident_90d"][rows] == index.labels["repeat_incident_90d"].index("Yes")).astype(float)
    n_labels = len(index.labels["fix_strategy"])
    n = np.bincount(fix_codes, minlength=n_labels)
    wins = np.bincount(fix_codes, weights=full, minlength=n_labels)
    anys = np.bincount(fix_codes, weights=anyrec, minlength=n_labels)
    reps = np.bincount(fix_codes, weights=repeat, minlength=n_labels)
    lower = wilson_lower(wins, n)
    upper = np.subtract(1.0, wilson_lower(np.subtract(n, wins), n))
    baseline = float(full.mean())
    num = {c: index.numeric[c][rows] for c in ("revenue_recovered_gbp", "days_to_recover", "time_to_fix_hours",
                                                "fix_cost_gbp", "return_on_fix", "conversion_recovery_ratio")}
    stats = []
    for code in np.flatnonzero(n >= min_n):
        sel = fix_codes == code
        name = index.labels["fix_strategy"][code]
        rate = wins[code] / n[code]
        stats.append({
            "fix": name, "key": FIX_BY_NAME[name], "cases": int(n[code]),
            "full_recovery_rate": safe_float(rate),
            "any_recovery_rate": safe_float(anys[code] / n[code]),
            "confidence_lower_bound": safe_float(lower[code]),
            "confidence_upper_bound": safe_float(upper[code]),
            "lift_vs_baseline": safe_float(rate / baseline if baseline > 0 else 0.0, 3),
            "repeat_rate_90d": safe_float(reps[code] / n[code]),
            "median_conversion_recovery": safe_float(np.median(num["conversion_recovery_ratio"][sel]), 3),
            "median_revenue_recovered_gbp": safe_float(np.median(num["revenue_recovered_gbp"][sel]), 0),
            "median_days_to_recover": safe_float(np.median(num["days_to_recover"][sel]), 1),
            "median_time_to_fix_hours": safe_float(np.median(num["time_to_fix_hours"][sel]), 1),
            "median_fix_cost_gbp": safe_float(np.median(num["fix_cost_gbp"][sel]), 0),
            "median_return_on_fix": safe_float(np.median(num["return_on_fix"][sel]), 1),
        })
    stats.sort(key=lambda s: (s["confidence_lower_bound"], s["cases"]), reverse=True)
    return stats, baseline


def timing_effect(index, rows, best_names):
    """Full recovery for fast versus slow responses among the best fixes."""
    if len(rows) == 0 or not best_names:
        return None
    codes = [c for c in (index.code_of("fix_strategy", nm) for nm in best_names) if c is not None]
    sel = rows[np.isin(index.codes["fix_strategy"][rows], codes)]
    if len(sel) < 30:
        return None
    hours = index.numeric["time_to_fix_hours"][sel] + index.numeric["detection_lag_hours"][sel]
    full = index.codes["recovery_status"][sel] == index.labels["recovery_status"].index("Full Recovery")
    cut = float(np.median(hours))
    fast, slow = full[hours <= cut], full[hours > cut]
    if len(fast) < 10 or len(slow) < 10:
        return None
    return {"threshold_hours": safe_float(cut, 1), "fast_full_recovery_rate": safe_float(fast.mean()),
            "slow_full_recovery_rate": safe_float(slow.mean()), "fast_cases": int(len(fast)),
            "slow_cases": int(len(slow))}


def outlook(index, rows):
    """What incidents of this kind typically cost, as a share of daily revenue."""
    if len(rows) == 0:
        return {}
    daily = np.maximum(index.numeric["baseline_daily_revenue_gbp"][rows], 1.0)
    days_lost = index.numeric["revenue_at_risk_gbp"][rows] / daily
    retention = index.numeric["conversion_retention_ratio"][rows]
    repeat = index.codes["repeat_incident_90d"][rows] == index.labels["repeat_incident_90d"].index("Yes")
    lag = index.numeric["detection_lag_hours"][rows]
    return {
        "cases": int(len(rows)),
        "median_conversion_retention": safe_float(np.median(retention), 3),
        "median_days_of_revenue_lost": safe_float(np.median(days_lost), 2),
        "p80_days_of_revenue_lost": safe_float(np.quantile(days_lost, 0.8), 2),
        "median_detection_lag_hours": safe_float(np.median(lag), 1),
        "repeat_rate_90d": safe_float(repeat.mean()),
    }


def split_recommendations(stats, baseline, top=3):
    """Recommend fixes that beat baseline with statistical support.

    A fix is flagged to avoid only when even the upper bound of its recovery rate
    sits below the baseline, so the avoid list is statistically confident too.
    Among those, the most commonly tried appear first, because they are the
    mistakes teams are most likely to repeat.
    """
    recommend = [s for s in stats if s["full_recovery_rate"] > baseline
                 and s["confidence_lower_bound"] >= 0.75 * baseline][:top]
    if not recommend and stats:
        recommend = stats[:1]
    avoid = [s for s in stats if s["confidence_upper_bound"] < baseline and s["cases"] >= 10
             and s["full_recovery_rate"] < 0.6 * baseline]
    avoid.sort(key=lambda s: s["cases"], reverse=True)
    return recommend, avoid[:2]


__all__ = ["reference_class", "fix_stats", "timing_effect", "outlook", "split_recommendations", "sub"]
